import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Planetscale Prisma and NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Planetscale, Prisma and NextJS
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>NextJS &rarr;</h2>
          </a>

          <a href="https://app.planetscale.com/" className={styles.card}>
            <h2>Planetscale &rarr;</h2>
          </a>

          <a href="https://www.prisma.io/" className={styles.card}>
            <h2>Prisma &rarr;</h2>
          </a>

          <a
            href="https://davidparks.dev/blog/planetscale-deployment-with-prisma/"
            className={styles.card}
          >
            <h2>The tutorial I followed &rarr;</h2>
          </a>
          <div>
            <Link href="/api/posts">
              <h2><a className={styles.card}>
                Try my api to retrieve posts from the DB &rarr;
              </a>
              </h2>
            </Link>
          </div>
          <div>
            <Link href="/api/users">
              <h2><a className={styles.card}>
                Try my api to retrieve users from the DB &rarr;
              </a>
              </h2>
            </Link>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
